name: CI

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Apercu
        uses: dev-celer/apercu-action
        env:
          NEON_PROJECT_ID: ${{ secrets.project_id }}
          NEON_API_KEY: ${{ secrets.api_key }}
        with:
          debug: true
