name: CI

on:
  pull_request:
    branches: [main]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Apercu
        uses: dev-celer/apercu-action@v0.1.0
        env:
          NEON_PROJECT_ID: ${{ secrets.project_id }}
          NEON_API_KEY: ${{ secrets.api_key }}
        with:
          debug: true
